In [1]:
import pandas as pd

df = pd.read_csv('Product Audit Table—Feminine Hygiene Products (Enugu).csv')
df.head(10)

,id,State,"Store Name: Name of supermarket, pharmacy, or stall",Location: address and area,"Product Brand Name: E.g., Always, Molped, LadyCare","Variants Available: Regular, night, long, etc.",Product Size: Total number of items in the pack,Price (#): Current shelf price (not promo price),Packaging Description: What does the packaging look/feel like?,Primary Color,...,Ziplock,Tags,"Key Claims on Pack: E.g., leak protection, ultra-thin, odor control",Key_claim theme,Eco-friendly Option: Yes/No (Does it promote sustainability?),Shelf Placement: Top / Mid / Bottom / Hidden,Visibility Rating: Low / Medium / High (Based on ease of spotting),"Promo Offer: Any discounts, bonus packs, or gift items?",Top Seller?: Input from vendor on sales rank or popularity,"Notes/Remarks: Other relevant info (e.g., product out of stock, observed consumer behavior)"
0,1,Enugu,Health plus pharmacy,Spar Enugu,Molped,Extra long,7,"1,770",Lightweight with a feminine color combo,NaN,...,no,Feminine Design,"Leak protection, Ultra soft, disinfected with ...",Absorbency & Protection; Comfort & Softness; I...,Yes,Bottom,low,No,Molped,Manufactured in nigeria
1,2,Enugu,Med plus pharmacy,Spar Enugu,Aya,Long,7,1200,"Comes with a stylish box with a clean,colorful...",NaN,...,no,"Stylish, Colorful","Super absorbent, extra long",Absorbency & Protection; Length & Size,Yes,Bottom,medium,NaN,Aya pad,Always was out of stock
2,3,Enugu,Med plus pharmacy,Spar Enugu,Angel pad,Regular,10,1200,Blue,Blue,...,no,NaN,Super absorbent,Absorbency & Protection,Yes,Bottom,low,NaN,No,Imported
3,4,Enugu,Medplus pharmacy,Spar Enugu,Ladycare,"Regular, Long",10,900,Yellow,Yellow,...,no,NaN,Now longer,Length & Size,Yes,Bottom,low,NaN,No,Made in Nigeria
4,5,Enugu,Spar,Spar Enugu,Aya,"Regular,large",10,925,A stylish box with a clean colorful design,NaN,...,no,"Stylish, Colorful","Super absorbent, No double ups",Absorbency & Protection; Innovation & Technology,Yes,Bottom,low,No,No,NaN
5,6,Enugu,Spar,Spar Enugu,Molped,Long,32,"3,555",Feminine color combo,NaN,...,no,Feminine Design,"Maxi thick, super absorbent",Absorbency & Protection; Length & Size,Yes,Middle,medium,NaN,Popular,Had more Molped pads in stock compared to others
6,7,Enugu,Spar,Spar Enugu,Always,Long,7,"1,365",Durable pink package,Pink,...,no,Durable,"Maxi thick, Gentle to skin, Protects from stain.",Comfort & Softness; Length & Size,No,Middle,medium,NaN,Nil,Nil
7,8,Enugu,Mc Chuks pharmacy,New heaven Enugu,Ladycare,Regular,8,1500,A green colored package,Green,...,no,NaN,Nil,Sustainability/Nil/No Claim,Yes,Hidden,low,None,No,Nil
8,9,Enugu,Mc Chuks pharmacy,New heaven enugu,Molped,"Regular, Long",8,1150,A portable purple package,Purple,...,no,Portable,"Maxi thick, skin friendly,super absorbent",Absorbency & Protection; Comfort & Softness; L...,Yes,Hidden,low,NaN,Popular,Consumers buy more of Molped pads and it's mad...
9,10,Enugu,Mc Chuks pharmacy,New heaven enugu,Softcare,"Regular, Long",30,2000,A compact resealable bag that makes it easy to...,NaN,...,yes,Compact,Breathable,Breathability & Ventilation,Yes,Bottom,low,5 free panty liners,Popular,Nil

In [3]:
df.columns

Index(['id', 'State', 'Store Name: Name of supermarket, pharmacy, or stall ',
       'Location: address and area ',
       'Product Brand Name: E.g., Always, Molped, LadyCare ',
       'Variants Available: Regular, night, long, etc. ',
       'Product Size: Total number of items in the pack ',
       'Price (#): Current shelf price (not promo price) ',
       'Packaging Description: What does the packaging look/feel like? ',
       'Primary Color', 'Secondary Color', 'Ziplock', 'Tags',
       'Key Claims on Pack: E.g., leak protection, ultra-thin, odor control ',
       'Key_claim theme',
       'Eco-friendly Option: Yes/No (Does it promote sustainability?) ',
       'Shelf Placement: Top / Mid / Bottom / Hidden ',
       'Visibility Rating: Low / Medium / High (Based on ease of spotting) ',
       'Promo Offer: Any discounts, bonus packs, or gift items? ',
       'Top Seller?: Input from vendor on sales rank or popularity ',
       'Notes/Remarks: Other relevant info (e.g., product out of stock, observed consumer behavior) '],
      dtype='object')

In [5]:
# Step 1: First, split the semicolon-separated themes into a list
df['Key_claim theme'] = df['Key_claim theme'].str.split("; ")

In [6]:
df.explode('Key_claim theme').reset_index(drop=True)

,id,State,"Store Name: Name of supermarket, pharmacy, or stall",Location: address and area,"Product Brand Name: E.g., Always, Molped, LadyCare","Variants Available: Regular, night, long, etc.",Product Size: Total number of items in the pack,Price (#): Current shelf price (not promo price),Packaging Description: What does the packaging look/feel like?,Primary Color,...,Ziplock,Tags,"Key Claims on Pack: E.g., leak protection, ultra-thin, odor control",Key_claim theme,Eco-friendly Option: Yes/No (Does it promote sustainability?),Shelf Placement: Top / Mid / Bottom / Hidden,Visibility Rating: Low / Medium / High (Based on ease of spotting),"Promo Offer: Any discounts, bonus packs, or gift items?",Top Seller?: Input from vendor on sales rank or popularity,"Notes/Remarks: Other relevant info (e.g., product out of stock, observed consumer behavior)"
0,1,Enugu,Health plus pharmacy,Spar Enugu,Molped,Extra long,7,"1,770",Lightweight with a feminine color combo,NaN,...,no,Feminine Design,"Leak protection, Ultra soft, disinfected with ...",Absorbency & Protection,Yes,Bottom,low,No,Molped,Manufactured in nigeria
1,1,Enugu,Health plus pharmacy,Spar Enugu,Molped,Extra long,7,"1,770",Lightweight with a feminine color combo,NaN,...,no,Feminine Design,"Leak protection, Ultra soft, disinfected with ...",Comfort & Softness,Yes,Bottom,low,No,Molped,Manufactured in nigeria
2,1,Enugu,Health plus pharmacy,Spar Enugu,Molped,Extra long,7,"1,770",Lightweight with a feminine color combo,NaN,...,no,Feminine Design,"Leak protection, Ultra soft, disinfected with ...",Innovation & Technology,Yes,Bottom,low,No,Molped,Manufactured in nigeria
3,2,Enugu,Med plus pharmacy,Spar Enugu,Aya,Long,7,1200,"Comes with a stylish box with a clean,colorful...",NaN,...,no,"Stylish, Colorful","Super absorbent, extra long",Absorbency & Protection,Yes,Bottom,medium,NaN,Aya pad,Always was out of stock
4,2,Enugu,Med plus pharmacy,Spar Enugu,Aya,Long,7,1200,"Comes with a stylish box with a clean,colorful...",NaN,...,no,"Stylish, Colorful","Super absorbent, extra long",Length & Size,Yes,Bottom,medium,NaN,Aya pad,Always was out of stock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,68,Enugu,Brotherly supermarket,Nsukka,Molped,Long,8,1100,Light purple and pink pack,Light Purple,...,no,NaN,"Skin friendly,Maxi thick,Absorbent",Length & Size,Yes,Hidden,low,NaN,Nil,Affordable for students
129,69,Enugu,Brotherly supermarket,Nsukka,Always,Extra long,7,"1,700",A pink pack,Pink,...,no,NaN,"Gentle to skin, cotton soft",Comfort & Softness,No,Hidden,low,NaN,NaN,A little bit low on sales
130,70,Enugu,Brotherly supermarket,Nsukka,Ladycare,"Regular, Long",10,1000,A yellow pack,Yellow,...,no,NaN,Now longer,Length & Size,Yes,Hidden,low,NaN,Nil,NaN
131,71,Enugu,Brotherly supermarket,Nsukka,Virony,"Regular, Long",30,2600,A light blue resealable zip lock bag that's ea...,Light Blue,...,yes,NaN,"High absorption rate, super thin",Absorbency & Protection,Yes,Hidden,low,5 free panty liners,Best seller,A little bit high in price for students
132,71,Enugu,Brotherly supermarket,Nsukka,Virony,"Regular, Long",30,2600,A light blue resealable zip lock bag that's ea...,Light Blue,...,yes,NaN,"High absorption rate, super thin",Length & Size,Yes,Hidden,low,5 free panty liners,Best seller,A little bit high in price for students