In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('lagos_explode.xlsx')

In [3]:
df.columns

Index(['Entry_id', 'Key Claims on Pack: E.g., leak protection, ultra-thin, odor control '], dtype='object')

In [4]:
# Step 1: #removing leading and trailing spaces
df['Key Claims on Pack: E.g., leak protection, ultra-thin, odor control '] = df['Key Claims on Pack: E.g., leak protection, ultra-thin, odor control '].str.strip()

In [5]:
# Step 1: #making all strings lower case
df['Key Claims on Pack: E.g., leak protection, ultra-thin, odor control '] = df['Key Claims on Pack: E.g., leak protection, ultra-thin, odor control '].str.lower()

In [6]:
# Step 1: First, split the semicolon-separated themes into a list
df['Key Claims on Pack: E.g., leak protection, ultra-thin, odor control '] = df['Key Claims on Pack: E.g., leak protection, ultra-thin, odor control '].str.split(", ")

In [7]:
df

,Entry_id,"Key Claims on Pack: E.g., leak protection, ultra-thin, odor control"
0,1,"[maxi thick, leak protection, nylon free, abso..."
1,2,"[locks wetness, locks odour, ultra thin, extra..."
2,3,"[massive absorption, 3d comfort fit, heavy flo..."
3,4,"[ultra soft, perfect protection perfume]"
4,5,[heavy flow]
...,...,...
76,77,[ultra thin]
77,78,[ultra thin]
78,79,[leak protection]
79,80,[ultra thin]
80,81,[ultra thin]

In [8]:
df = df.explode('Key Claims on Pack: E.g., leak protection, ultra-thin, odor control ').reset_index(drop=True)
df

,Entry_id,"Key Claims on Pack: E.g., leak protection, ultra-thin, odor control"
0,1,maxi thick
1,1,leak protection
2,1,nylon free
3,1,absorbs 3x of its weight
4,2,locks wetness
...,...,...
137,77,ultra thin
138,78,ultra thin
139,79,leak protection
140,80,ultra thin
141,81,ultra thin

In [9]:
# Save to Excel
df.to_excel('lagos_exploded.xlsx', index=False)